# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys

curr_path = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, curr_path)
sys.path.insert(0, os.path.abspath(os.path.join(curr_path, '../../src')))

# noqa: E402 — отключаем flake8 ругань только тут
from custom_stuff.skip_methods import skip_methods  # noqa: E402
from custom_stuff.navigation_settings import sidebar_settings  # noqa: E402

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project_name = 'SS Python Docs'
project = project_name
copyright = '2024, ROGII'
author = 'ROGII'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'autoapi.extension',
    'custom_stuff.sphinx_displayname_extension',
    'sphinx.ext.intersphinx',
    'sphinx_copybutton',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_static_path = ['_static']
html_theme = 'furo'
html_favicon = '_static/favicon.svg'
html_logo = '_static/logo.svg'
html_css_files = ['custom.css']
html_js_files = ['replace_logo.js']
html_title = project_name
html_show_sourcelink = False
html_show_sphinx = False
add_module_names = False
html_sidebars = {
    "**": [
        "sidebar/scroll-start.html",
        "sidebar/brand.html",
        "sidebar/search.html",
        "navigation.html",
        "sidebar/ethical-ads.html",
        "sidebar/scroll-end.html",
    ]
}

# Creating html for property/method
rst_prolog = """
.. role:: summarylabel-method
.. role:: summarylabel-property
"""
intersphinx_mapping = {'python': ('https://docs.python.org/3.12', None)}

# Change the main page of the documentation
master_doc = 'autoapi/index'
autodoc_typehints = 'signature'
IN_DOCKER = os.environ.get("IN_DOCKER") == "true"

if IN_DOCKER:
    autoapi_dirs = ['/app/src']
else:
    autoapi_dirs = [os.path.abspath(os.path.join(os.path.dirname(__file__), '../../src'))]

print("IN_DOCKER:", IN_DOCKER)
print("autoapi_dirs =", autoapi_dirs)

autoapi_template_dir = "_templates/autoapi"
autoapi_type = "python"

# Delete the autogenerated rst. For debugging, it is possible to set True.
autoapi_keep_files = False
autoapi_options = [
    "members",
    "undoc-members",
    "special-members",
    "show-inheritance",
    "show-module-summary",
    "imported-members",
    'inherited-members',
]


def setup(sphinx):
    sphinx.connect("html-page-context", sidebar_settings)
    sphinx.connect("autoapi-skip-member", skip_methods)
