default:
  image: python:3.10
  tags:
    - docker
    - ubuntu
  before_script:
    - pip install --upgrade pip
    - pip install .[dev]

stages:
  - test
  - build
  - publish

test:
  stage: test
  rules:
    - when: manual
  script:
    - pre-commit run --all-files
    - pytest tests/main --verbosity=1

build:
  stage: build
  rules:
    - when: on_success
  script:
    - python -m build
  artifacts:
    paths:
      - dist/
    expire_in: 1d

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PYPI_TOKEN
  script:
    - twine upload dist/* --verbose
