default:
  image: python:3.10
  tags:
    - docker
    - ubuntu

include:
  - project: "infra/ci-templates"
    ref: "master"
    file:
      - rules.yml
      - vault_auth.yml
      - build.yml
      - deploy_k8s.yml
      - deploy_k8s/envs/deploy_kubesolo_k8s.yml
      - deploy_k8s/envs/deploy_aws_k8s.yml

stages:
  - test
  - build
  - publish
  - deploy

test:
  stage: test
  rules:
    - when: manual
  before_script:
    - pip install --upgrade pip
    - pip install .[dev]
  script:
    - pre-commit run --all-files
    - pytest tests/main --verbosity=1

build:
  stage: build
  before_script:
    - pip install --upgrade pip
    - pip install .[dev]
  script:
    - python -m build
  artifacts:
    paths:
      - dist/
    expire_in: 1d

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PYPI_TOKEN
  before_script:
    - pip install --upgrade pip
    - pip install .[dev]
  script:
    - twine upload dist/* --verbose

build_python_docs:
  extends:
    - .build_docker_template
  variables:
    BUILD_CONTEXT: ${CI_PROJECT_DIR}
    DOCKER_FILE: ${CI_PROJECT_DIR}/docs/Dockerfile
    DOCKER_REPO: ${CI_REGISTRY_IMAGE}/python-docs
  rules:
    - !reference [.rules_template, web_manual]

.deploy_variables:
  variables:
    KUBERNETES_NAMESPACE_OVERWRITE: python-docs
    K8S_DEPLOYMENT_DIR: rogii/python-docs
    DEPLOY_COMPONENTS: "python-docs"
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/python-docs
  needs:
    - build_python_docs
  rules:
    - !reference [.rules_template, web_manual]

deploy_awsstaging_k8s:
  rules: [when: never]

deploy_kubesolo_k8s:
  environment:
    name: kubesolo
    url: https://python.rogii.net

deploy_awsprod_k8s:
  environment:
    name: awsprod
    url: https://python.solo.cloud
