stages:
  - publish

variables:
  CI_REF: &ref master
  PYTHON_VERSION: "3.8"
  IMAGE_NAME: python

include:
  # templates
  - { project: 'infra/ci-templates', ref: *ref, file: 'pypi_package.yml' }
  -
publish:
  extends:
    - .pypi_package
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(?:\.\d+)?$/'
      when: always
      allow_failure: false
