server {
    listen 80;
    server_name ${DOCS_DOMAIN};
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    location = / {
        return 302 /autoapi/index.html;
    }
}