server {
    listen 80;
    server_name ${DOCS_DOMAIN};
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;

        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        add_header Pragma "no-cache";
        expires 0;
    }

    location = / {
        return 302 /autoapi/index.html;
    }
}
